### ISSUE TITLE
Unknown error with meteortoys email?

### ISSUE THREAD

**Issue by Floriferous** [MeteorToys/allthings#111]
I'm seeing an error that I can't inspect from meteor-toys email (even though I'm not using the pro version):

<img width="1453" alt="screen shot 2018-09-17 at 10 12 09" src="https://user-images.githubusercontent.com/10428082/45613210-d6064b00-ba65-11e8-862d-3d4d0af7fa63.png">

When I try to add a try-catch block closer to the source, I just keep seeing this `[object object]` error.

**Comment by Floriferous** [comment]
Okay, here's the actual error:

```sh
I20181012-16:21:57.294(2)? Exception while invoking method 'myMethod' ReferenceError: MeteorToys is not defined
I20181012-16:21:57.294(2)?     at eval (eval at Collection (packages/msavin_mongol.js:150:29), <anonymous>:1:1)
I20181012-16:21:57.295(2)?     at Object.Collection (packages/msavin_mongol.js:150:29)
I20181012-16:21:57.295(2)?     at MethodInvocation.Mongol_insert (packages/msavin_mongol.js:210:4190)
I20181012-16:21:57.295(2)?     at MethodInvocation.methodMap.(anonymous function) (packages/lmachens_kadira.js:2726:30)
I20181012-16:21:57.295(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20181012-16:21:57.295(2)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)
I20181012-16:21:57.295(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20181012-16:21:57.295(2)?     at resolve (packages/ddp-server/livedata_server.js:1683:36)
I20181012-16:21:57.295(2)?     at new Promise (<anonymous>)
I20181012-16:21:57.295(2)?     at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)
I20181012-16:21:57.296(2)?     at Server.apply (packages/ddp-server/livedata_server.js:1621:26)
I20181012-16:21:57.296(2)?     at Server.call (packages/ddp-server/livedata_server.js:1603:17)
I20181012-16:21:57.296(2)?     at Object.Email.(anonymous function) (packages/meteortoys_email.js:23:700)
I20181012-16:21:57.296(2)?     at Object.Email.send (packages/lmachens_kadira.js:3500:28)
I20181012-16:21:57.296(2)?     at AccountsServer.Accounts.sendEnrollmentEmail (packages/accounts-password/password_server.js:765:9)
I20181012-16:21:57.296(2)?     at Service._defineProperty [as sendEnrollmentEmail] (imports/core/myFile.js:68:16)
```

**Comment by mishantidev** [comment]
I've got the same error!

**Comment by Floriferous** [comment]
Update on this? We're still experiencing it.

**Comment by Floriferous** [comment]
@msavin Maybe it's time to make this package open source? We're stuck with this and can't even fork the package.

**Comment by SantoshSrinivas79** [comment]
@msavin any suggestion? getting same error
