### ISSUE TITLE
Cannot upgrade to v1.2.3 due to isopack error

### ISSUE THREAD

**Issue by mordrax** [MeteorToys/allthings#24]
Anyone else getting this? I'm not so sure it's meteortoys related but this is happening when I upgrade to v1.2.3. 

And there's very little on google about it which makes me suspect I'm doing something wrong here.

```
Error: Could not find isopack data with format isopack-1.
This isopack was likely built with a much newer version of Meteor.
    at Function.readMetadataFromDirectory (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\isopack.js:323:13)
    at [object Object]._.extend._alreadyDownloaded (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\tropohouse.js:319:35)
    at [object Object]._.extend._makeDownloader (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\tropohouse.js:383:33)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\tropohouse.js:524:29
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\tropohouse.js:521:20
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\package-map.js:50:7
    at Function._.each._.forEach (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at [object Object]._.extend.eachPackage (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\package-map.js:42:7)
    at [object Object]._.extend.downloadPackagesMissingFromMap (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\tropohouse.js:518:16)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:668:25
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:667:20
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\catalog.js:100:5
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:666:13)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:238:35
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:352:18
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:345:34
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:343:23
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.enterJob (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:317:26)
    at ProjectContext._.extend._completeStagesThrough (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:228:18)
    at ProjectContext._.extend.saveChangedMetadata (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:216:10)
    at ProjectContext._.extend.prepareProjectForBuild (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\project-context.js:221:10)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\commands-packages.js:1878:20
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:264:13
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:257:29
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:255:18
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:246:23
    at [object Object]._.extend.withValue (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\fiber-helpers.js:115:14)
    at Object.capture (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\buildmessage.js:245:19)
    at Command.main.registerCommand.name [as func] (C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\commands-packages.js:1877:27)
    at C:\Users\mordrax\AppData\Local\.meteor\packages\meteor-tool\1.1.4\mt-os.windows.x86_32\tools\main.js:1363:23
```

Here are my packages:

```
meteor-platform
accounts-ui
accounts-password
accounts-google
accounts-twitter
accounts-github
wylio:mandrill
mquandalle:jade
iron:router
aldeed:autoform
aldeed:simple-schema
aldeed:collection2
dburles:collection-helpers
matb33:collection-hooks
alanning:roles
ongoworks:security
useraccounts:bootstrap
differential:event-hooks
momentjs:moment
raix:push
twbs:bootstrap
mrt:flash-messages
ovcharik:favico
fortawesome:fontawesome
okgrow:iron-router-autoscroll
summernote:summernote
mpowaga:autoform-summernote
zimme:iron-router-auth
djedi:sanitize-html
yogiben:admin
matteodem:easy-search
underscorestring:underscore.string
coffeescript
reactive-dict
jeanfredrik:denormalize
reactive-var
reywood:publish-composite
gwendall:template-states
aldeed:autoform-select2
react-template-helper
react
```

**Comment by mordrax** [comment]
Actually, since I removed 1.2.1, I can't add it anymore, it's happening for all versions of meteortoys :(

**Comment by mordrax** [comment]
Reinstalled meteor, errors disappeared. Am on 1.2.3, woohooo!
