### ISSUE TITLE
Conflicts with Unirecorder?

### ISSUE THREAD

**Issue by rngadam** [MeteorToys/allthings#54]
after `meteor add meteortoys:allthings`, tried running my project and have this failure:

```
I20151103-14:19:59.980(8)? ======== Universe Audio Recorder ========
W20151103-14:19:59.980(8)? (STDERR) This package needs an cross-platform SoX utility, without SoX only .wav will be supported
W20151103-14:19:59.981(8)? (STDERR) TIP: Install on ubuntu: sudo apt-get install sox
W20151103-14:20:00.120(8)? (STDERR) 
W20151103-14:20:00.120(8)? (STDERR) /Users/rngadam/.meteor/packages/meteor-tool/.1.1.10.uq9x91++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151103-14:20:00.120(8)? (STDERR)                         throw(ex);
W20151103-14:20:00.121(8)? (STDERR)                               ^
W20151103-14:20:00.133(8)? (STDERR) Error: use "new" to construct a Mongo.Collection
W20151103-14:20:00.133(8)? (STDERR)     at [object Object].Mongo.Collection (packages/mongo/collection.js:29:1)
W20151103-14:20:00.133(8)? (STDERR)     at [object Object].ns.Collection (packages/lai_collection-extensions/packages/lai_collection-extensions.js:79:1)
W20151103-14:20:00.133(8)? (STDERR)     at new UniCollection (packages/vazco_universe-collection/packages/vazco_universe-collection.js:14:1)
W20151103-14:20:00.133(8)? (STDERR)     at new UniRecorder (packages/universe_audio-recorder/packages/universe_audio-recorder.js:30:1)
W20151103-14:20:00.133(8)? (STDERR)     at lib/common.js:2:9
W20151103-14:20:00.134(8)? (STDERR)     at /Users/rngadam/hackacademy/ls/src/bookreader/.meteor/local/build/programs/server/app/lib/common.js:31:4
W20151103-14:20:00.134(8)? (STDERR)     at /Users/rngadam/hackacademy/ls/src/bookreader/.meteor/local/build/programs/server/boot.js:242:10
W20151103-14:20:00.134(8)? (STDERR)     at Array.forEach (native)
W20151103-14:20:00.134(8)? (STDERR)     at Function._.each._.forEach (/Users/rngadam/.meteor/packages/meteor-tool/.1.1.10.uq9x91++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151103-14:20:00.135(8)? (STDERR)     at /Users/rngadam/hackacademy/ls/src/bookreader/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

after `meteor remove meteortoys:allthings`, the project works.

**Comment by msavin** [comment]
Hey man - sorry you are having an issue with this. Can you try to move the meteor toys package to the top of your package list, and seeing if that helps. 

To do that, go to ./meteor/packages and edit the file

**Comment by jamielob** [comment]
@msavin FYI - I had a similar problem with 2.2 breaking meteorhacks:aggregate - moving it to the top of the packages list manually fixed it for me.

**Comment by msavin** [comment]
Thanks for the tip @jamielob 
Assuming this got it working, so will close the issue.
