### ISSUE TITLE
"Blueprint" Orb MouseOUT Causes Console Error

### ISSUE THREAD

**Issue by abernix** [MeteorToys/allthings#61]
Every time I remove my mouse from hovering over the "Blueprint" orb, the following message is printed to my console...

```
Exception in template helper: TypeError: Cannot read property 'name' of null
    at String.Template.(anonymous function).(anonymous function).content (http://localhost:3200/packages/meteor:/💻app/packages/meteortoys_blueprint/client/main.js:1:1)
    at http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:2958:1
    at http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1622:1
    at http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3010:1
    at Function.Template._withTemplateInstanceFunc (http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3643:1)
    at http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:3009:1
    at Object.Spacebars.call (http://localhost:3200/packages/meteor:/💻app/packages/spacebars/packages/spacebars.js:141:1)
    at http://localhost:3200/packages/meteor:/💻app/packages/meteortoys_blueprint/client/template.main.js:44:1
    at [object Object].<anonymous> (http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:2646:1)
    at http://localhost:3200/packages/meteor:/💻app/packages/blaze/packages/blaze.js:1844:1
```

The problem seems to go away if I click on the orb (which brings up "Blueprint")

Chrome Version 47.0.2526.73 (64-bit) Mac OS X

<img width="171" alt="screen shot 2015-12-02 at 5 06 17 pm" src="https://cloud.githubusercontent.com/assets/841294/11534494/afbf94b4-9917-11e5-914d-4ee91ef18b7b.png">

**Comment by rhyslbw** [comment]
+1

**Comment by msavin** [comment]
Fix coming soon. Please note its a type error and will not cause any harm - though I do understand it could be annoying.

**Comment by abernix** [comment]
Thanks – yes, aware. ;)

**Comment by msavin** [comment]
This issue has been resolved in Meteor Toys 3, and your new activation code should be in your inbox. Please upgrade and let me know how it works. If you experience any issues, please open a new issue.
