### ISSUE TITLE
Exception in MeteorToys_x with every Meteor server restart, version 3.0.0

### ISSUE THREAD

**Issue by JanMP** [MeteorToys/allthings#77]
Exception while invoking method 'MeteorToys_x' ReferenceError: Match is not defined
   at [object Object].Meteor.(anonymous function).MeteorToys_x (packages/meteortoys_method/server/main.js:1:1)
   at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
   at packages/ddp-server/livedata_server.js:711:19
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at packages/ddp-server/livedata_server.js:709:40
   at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
   at packages/ddp-server/livedata_server.js:707:46
   at tryCallTwo (/Users/pille/.meteor/packages/promise/.0.6.7.1jhi79i++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
   at doResolve (/Users/pille/.meteor/packages/promise/.0.6.7.1jhi79i++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
   at new Promise (/Users/pille/.meteor/packages/promise/.0.6.7.1jhi79i++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)

**Comment by ramijarrar** [comment]
We are seeing the same error

**Comment by msavin** [comment]
This should be fixed with the latest update. Please remove and add the package and let me know how it works.

**Comment by AlexCatch** [comment]
I can confirm it's been fixed.

**Comment by JanMP** [comment]
Yes, looks fine now. Thanks.
