### ISSUE TITLE
Using Meteor toys pro along Redis-oplog

### ISSUE THREAD

**Issue by Fen747** [MeteorToys/allthings#94]
Using redis-oplog in the same project than meteor toys Pro, after I did a `meteor update` from 1.4.2.3 to 1.4.2.7 (and almost all the packages in my app), I now get this when I start my app :

```
Exception while invoking method 'MeteorToys_impersonate_account' { stack: 'TypeError: Cannot read property \'find\' of undefined\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/actions/requery.js:14:22)\n    at handleRemove (packages/cultofcoders:redis-oplog/lib/processors/limit-sort.js:72:9)\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/processors/limit-sort.js:20:13)\n    at RedisSubscriber.processSync (packages/cultofcoders:redis-oplog/lib/redis/RedisSubscriber.js:65:9)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:19:28\n    at Array.forEach (native)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:18:25\n    at Array.forEach (native)\n    at module.export.exports.default (packages/cultofcoders:redis-oplog/lib/mongo/lib/compensateForLatency.js:13:14)\n    at packages/cultofcoders:redis-oplog/lib/mongo/lib/dispatchers.js:36:9',
I20170216-13:00:38.373(1)?   source: 'method' }
```

`versions` file before the update (1.4.2.3) : http://pastebin.com/CR9MxWhC
`versions` file after the update (1.4.2.7) : http://pastebin.com/8vuKXyHM

**Comment by msavin** [comment]
How are you liking that package? Does removing it make Toys work?

**Comment by Fen747** [comment]
Yes it works well when I remove redis-oplog.

**Comment by msavin** [comment]
I haven't used the package so it's hard for me to identify the issue. I'm
going to look into it soon, but in meanwhile, going to loop in @theodorDiaconu
maybe it's helpful for him to know and/or maybe he could provide some
insight into the problem

**Comment by theodorDiaconu** [comment]
Interesting bug. Will look into it.

**Comment by theodorDiaconu** [comment]
@msavin I think I may be on to something, give me a bit of insight of what kind of collections meteor toy uses ? Are they local collections ?

**Comment by msavin** [comment]
@Fen747 hey man- there is a new version that had big changes- maybe it makes difference?

@theodorDiaconu ah, MT is using this package, which may be problem? 
https://github.com/dburles/mongo-collection-instances

**Comment by theodorDiaconu** [comment]
@msavin most likely yes, the reason was that meteortoys needs to be added after redis-oplog.

**Comment by msavin** [comment]
@Fen747  hey man - did @theodorDiaconu recommendation help you get back into using Meteor Toys?
