### ISSUE TITLE
Mongol update error using Simple-Schema / Collection2

### ISSUE THREAD

**Issue by ppedrazzi** [MeteorToys/allthings#98]
Mongol remove and duplicate work fine, but update fails for any changes.  I get the following:

`Exception while invoking method 'Mongol_update' Error: Expected 'name' to be a modifier operator like '$set'`

I imagine this is due to some setting in Simple-Schema or Collection2.  Have you seen this before?

**Comment by msavin** [comment]
This is now working with the new Mongol 4.0. Just update the package and you should be good to go :)

Meteor Toys has also been patched up to work in these situations, I will be sending the new keys out shortly. 

If you run into any issues, please let me know.

**Comment by Floriferous** [comment]
I updated to 4.0.0 and still get this error, haven't been able to use the meteortoys update feature for a few months now.

Here is my stack trace:

```bash
Exception while invoking method 'Mongol_update' Error: Expected 'general' to be a modifier operator like '$set'
I20170627-16:02:36.392(2)?     at /Users/Florian/dev/epotek/node_modules/simpl-schema/dist/doValidation.js:312:15
I20170627-16:02:36.393(2)?     at Function._.each._.forEach (/Users/Florian/dev/epotek/node_modules/simpl-schema/node_modules/underscore/underscore.js:158:9)
I20170627-16:02:36.393(2)?     at checkModifier (/Users/Florian/dev/epotek/node_modules/simpl-schema/dist/doValidation.js:309:26)
I20170627-16:02:36.394(2)?     at doValidation (/Users/Florian/dev/epotek/node_modules/simpl-schema/dist/doValidation.js:351:5)
I20170627-16:02:36.395(2)?     at ValidationContext.validate (/Users/Florian/dev/epotek/node_modules/simpl-schema/dist/ValidationContext.js:217:57)
I20170627-16:02:36.396(2)?     at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:399:33)
I20170627-16:02:36.397(2)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2-core/collection2.js:187:25)
I20170627-16:02:36.398(2)?     at [object Object].Meteor.(anonymous function).Mongol_update (packages/msavin_mongol.js:40:2919)
I20170627-16:02:36.398(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170627-16:02:36.399(2)?     at packages/ddp-server/livedata_server.js:719:19
```

Any ideas?

**Comment by alexpanov** [comment]
I am getting an error with Simple Schema too.

After trying to modify a document, I get this error in the Meteor console:

```
I20171112-16:31:11.604(-5)? Exception while invoking method 'Mongol_update' Error: When the modifier option is true, all validation object keys must be operators. Did you forget `$set`?
I20171112-16:31:11.604(-5)?     at packages/aldeed_simple-schema.js:2466:15
I20171112-16:31:11.605(-5)?     at Function._.each._.forEach (packages/underscore.js:147:22)
I20171112-16:31:11.605(-5)?     at checkModifier (packages/aldeed_simple-schema.js:2463:7)
I20171112-16:31:11.605(-5)?     at doValidation1 (packages/aldeed_simple-schema.js:2495:5)
I20171112-16:31:11.605(-5)?     at doValidation (packages/aldeed_simple-schema.js:2910:10)
I20171112-16:31:11.605(-5)?     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed_simple-schema.js:2945:21)
I20171112-16:31:11.605(-5)?     at Mongo.Collection.doValidate (packages/aldeed_collection2-core.js:426:33)
I20171112-16:31:11.605(-5)?     at Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:214:25)
I20171112-16:31:11.605(-5)?     at DDPCommon.MethodInvocation.Mongol_update (packages/msavin_mongol.js:40:2919)
I20171112-16:31:11.605(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
```

Please help. I haven't been able to use Meteor Toys to it's fullest
